import { useState } from 'react';
import { Navigation } from '../components/Navigation';
import { Compass, Users, Calendar, Sparkles, Check, ArrowRight, CloudSun, Banknote } from 'lucide-react';
import { Link } from 'react-router';
import { tripPlannerAPI, type TripPlan } from '../api/travelApi';
import { useAuth } from '../context/AuthContext';

export function TripPlanner() {
  const { isAuthenticated } = useAuth();
  const [budget, setBudget] = useState('');
  const [duration, setDuration] = useState('');
  const [travelers, setTravelers] = useState('');
  const [interests, setInterests] = useState<string[]>([]);
  const [plan, setPlan] = useState<TripPlan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const interestOptions = [
    'Wildlife & Safaris',
    'Culture & History',
    'Adventure Sports',
    'Relaxation',
    'Photography',
    'Local Cuisine',
  ];

  const toggleInterest = (interest: string) => {
    setInterests((prev) =>
      prev.includes(interest) ? prev.filter((item) => item !== interest) : [...prev, interest],
    );
  };

  const generatePlan = async () => {
    try {
      setLoading(true);
      setError(null);
      const nextPlan = await tripPlannerAPI.generatePlan({
        budget: Number(budget),
        duration: Number(duration),
        travelers: Number(travelers),
        interests,
      });
      setPlan(nextPlan);
    } catch {
      setError('We could not generate a live plan right now.');
    } finally {
      setLoading(false);
    }
  };

  const canGenerate = budget && duration && travelers && interests.length > 0;

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />

      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-green-600 rounded-lg flex items-center justify-center">
              <Compass className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-4xl font-bold text-gray-900">AI Trip Planner</h1>
              <p className="text-gray-600">Trip plans are now generated by the backend using live travel, weather, and exchange-rate context.</p>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200 h-fit">
            <h2 className="text-xl font-semibold text-gray-900 mb-6">Your Travel Details</h2>

            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Total Budget (USD)</label>
                <input
                  type="number"
                  value={budget}
                  onChange={(event) => setBudget(event.target.value)}
                  placeholder="e.g. 3000"
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Trip Duration (days)</label>
                <div className="relative">
                  <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="number"
                    value={duration}
                    onChange={(event) => setDuration(event.target.value)}
                    placeholder="e.g. 7"
                    className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Number of Travelers</label>
                <div className="relative">
                  <Users className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="number"
                    value={travelers}
                    onChange={(event) => setTravelers(event.target.value)}
                    placeholder="e.g. 2"
                    className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Your Interests</label>
                <div className="grid grid-cols-2 gap-2">
                  {interestOptions.map((interest) => (
                    <button
                      key={interest}
                      onClick={() => toggleInterest(interest)}
                      className={`px-4 py-2 rounded-lg border-2 transition-all ${
                        interests.includes(interest)
                          ? 'border-green-500 bg-green-50 text-green-700'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      {interest}
                    </button>
                  ))}
                </div>
              </div>

              <button
                onClick={generatePlan}
                disabled={!canGenerate || loading}
                className="w-full bg-gradient-to-r from-green-600 to-green-700 text-white py-4 rounded-lg font-semibold flex items-center justify-center gap-2 hover:from-green-700 hover:to-green-800 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Building live trip plan...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    Generate My Plan
                  </>
                )}
              </button>

              {error && <div className="rounded-lg bg-red-50 border border-red-200 p-4 text-red-700">{error}</div>}
            </div>
          </div>

          <div>
            {!plan && !loading && (
              <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-8 border border-green-200 text-center">
                <Sparkles className="w-16 h-16 text-green-600 mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Backend-Powered Recommendations</h3>
                <p className="text-gray-600">
                  Fill in your travel details and the backend will assemble a plan using live API data instead of static bundles.
                </p>
              </div>
            )}

            {plan && !isAuthenticated && (
              <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-8 border border-green-200 text-center shadow-lg">
                <Sparkles className="w-16 h-16 text-green-600 mx-auto mb-4 animate-pulse" />
                <h3 className="text-2xl font-bold text-gray-900 mb-4">Your AI Trip Plan is Ready!</h3>
                <p className="text-gray-600 mb-8 text-lg">
                  We've generated a customized itinerary based on your preferences, budget, and live travel data. Please log in or create an account to view and save your plan.
                </p>
                <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                  <Link
                    to="/login"
                    className="w-full sm:w-auto px-8 py-3 bg-gradient-to-r from-green-600 via-green-500 to-green-600 bg-[length:200%_auto] animate-gradient text-white rounded-lg font-semibold hover:shadow-lg transition-all"
                  >
                    Log In to View Plan
                  </Link>
                  <Link
                    to="/login"
                    className="w-full sm:w-auto px-8 py-3 bg-white text-green-700 border-2 border-green-700 rounded-lg font-semibold hover:bg-green-50 transition-colors"
                  >
                    Create Account
                  </Link>
                </div>
              </div>
            )}

            {plan && isAuthenticated && (
              <div className="space-y-6">
                <div className="bg-gradient-to-br from-green-600 to-green-700 rounded-xl p-6 text-white">
                  <div className="flex items-center gap-2 mb-2">
                    <Check className="w-6 h-6" />
                    <h3 className="text-xl font-semibold">Your Personalized Plan</h3>
                  </div>
                  <p className="text-green-100">
                    Based on ${budget} for {duration} days with {travelers} traveler(s)
                  </p>
                  <div className="mt-4 pt-4 border-t border-green-500">
                    <p className="text-sm text-green-100">Daily budget per person</p>
                    <p className="text-3xl font-bold">${plan.dailyBudget}</p>
                  </div>
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                  <div className="bg-white rounded-xl p-5 shadow-sm border border-gray-200">
                    <div className="flex items-center gap-2 mb-2">
                      <CloudSun className="w-5 h-5 text-blue-600" />
                      <h3 className="font-semibold text-gray-900">Live Weather</h3>
                    </div>
                    <p className="text-gray-700">{plan.liveContext.weather.city}: {plan.liveContext.weather.temperature}°C, {plan.liveContext.weather.description}</p>
                  </div>
                  <div className="bg-white rounded-xl p-5 shadow-sm border border-gray-200">
                    <div className="flex items-center gap-2 mb-2">
                      <Banknote className="w-5 h-5 text-green-600" />
                      <h3 className="font-semibold text-gray-900">Exchange Rate</h3>
                    </div>
                    <p className="text-gray-700">1 USD ≈ {plan.liveContext.exchangeRates.usdToRwf} RWF</p>
                  </div>
                </div>

                <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
                  <h3 className="font-semibold text-gray-900 mb-4">Recommended Accommodation</h3>
                  <ul className="space-y-2">
                    {plan.accommodation.map((item) => (
                      <li key={item} className="flex items-start gap-2 text-gray-700">
                        <Check className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
                  <h3 className="font-semibold text-gray-900 mb-4">Suggested Activities</h3>
                  <ul className="space-y-2">
                    {plan.activities.map((item) => (
                      <li key={item} className="flex items-start gap-2 text-gray-700">
                        <Check className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
                  <h3 className="font-semibold text-gray-900 mb-4">Food & Dining</h3>
                  <ul className="space-y-2">
                    {plan.food.map((item) => (
                      <li key={item} className="flex items-start gap-2 text-gray-700">
                        <Check className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
                  <h3 className="font-semibold text-gray-900 mb-4">Transportation</h3>
                  <p className="text-gray-700">{plan.transport}</p>
                </div>

                <Link
                  to="/my-itinerary"
                  className="w-full bg-green-600 text-white py-4 rounded-lg font-semibold flex items-center justify-center gap-2 hover:bg-green-700 transition-colors"
                >
                  Save to My Itinerary
                  <ArrowRight className="w-5 h-5" />
                </Link>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
